# Effects that will be applied to dead players
when-dead:

  # If enabled, dead players won't be able to move.
  freeze: true

  # If enabled, dead players will have Blindness effect.
  blind: true

# If enabled, players will pop out particles when getting revived, they can also customize their particles with /particles
revive-particles: true

# If enabled, dead players will be able to get revived, even while they are offline.
# You can't revive someone offline yet. so don't mess with this.
offline-revives: false

# Features.
features:

  # Enables /friend command.
  friend: true

  # Enabled /team command.
  team: true

# Announcement options
announcements:

  # If enabled, everyone will get announcements when someone gets revived.
  revives: false

  # If enabled, everyone will get announcements when someone crafts a revive head.
  crafts: false

  # If enabled, everyone will get announcements when someone gets killed and drops his head, even while showDeathMessages are off.
  kills: false

# Customize Revive Head's recipe
recipe:

  # If enabled, everything will be ignored and default recipe will be used.
  use-default: true

  # Recipe's shape. Every letter is a symbol of a material. Customize these symbols and their materials in 'materials' to use them in this shape.
  shape:
    - 'DND'
    - 'TWT'
    - 'DND'

  # All materials that should be used inside 'shape'. See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for all materials.
  materials:
    D: 'DIAMOND_BLOCK'
    T: 'TOTEM_OF_UNDYING'
    W: 'NETHER_STAR'
    N: 'NETHERITE_INGOT'
    a: 'AIR'